homework done
KlimovDima/cycle2 pull request #1
Opened 2023-03-16 00:41 UTC by KlimovDima

Продолжили знакомство с циклами

2023-03-16 10:31 UTC, safgbad requested changes

2023-03-16 10:31 UTC, safgbad commented on src/Main.java
> +            System.out.println("Сумма накоплений за: " + month + " месяц равна " + amountMoney + " рублей");
`amountMoney = amountMoney + deposit;`
можно короче:
`amountMoney += deposit;`

2023-03-16 10:31 UTC, safgbad commented on src/Main.java
> +        int deathInYear;
я бы не инициализировал эти переменные вне цикла
можно прямо в цикле 
`int bornInYear = population / 1000 * natality;`
`int deathInYear = population / 1000 * deathRate;`

2023-03-16 10:31 UTC, safgbad commented on src/Main.java
> +        int month = 0;
копейка рубль бережет и поэтому money все-таки double должна быть
касается и следующих задач

2023-03-16 10:31 UTC, safgbad commented on src/Main.java
> +            money = (int) (money * percentMonth) + money;
вообще там не говорилось, что Василий (или как его там) кладет каждый месяц по 15к
он однажды только положил
касается и двух следующих задач

2023-03-16 10:31 UTC, safgbad commented on src/Main.java
> +            money = money + depositMonth;
тут лучше использовать цикл for, не нужно будет в теле цикла каждый раз month увеличивать

2023-03-16 10:31 UTC, safgbad commented on src/Main.java
> +            System.out.println("Сегодня пятница " + dayOneFriday + " -е число. Необходимо подготовить отчёт");
намудрил
через for будет гораздо проще (типа начиная с первой пятницы и до 31 числа с шагом 7 идешь и выводишь сообщение)

2023-03-16 10:31 UTC, safgbad commented on src/Main.java
> +            yearFlyComet = yearFlyComet + cycleComet;
почему 2100, а не endYearComet?

тут опять же лучше с циклом for работать (начиная с 0 года заканчивая endYearComet с шагом cycleComet; внутри условие, чтобы год был больше или равен startYearComet => вывод года в консоль)

2023-03-19 21:12 UTC, KlimovDima commented on src/Main.java
> +        int deathInYear;
compete

2023-03-19 21:12 UTC, KlimovDima commented on src/Main.java
> +        int month = 0;
compete

2023-03-19 21:12 UTC, KlimovDima commented on src/Main.java
> +            money = (int) (money * percentMonth) + money;
compete

2023-03-19 21:13 UTC, KlimovDima commented on src/Main.java
> +            money = money + depositMonth;
compete

2023-03-19 21:13 UTC, KlimovDima commented on src/Main.java
> +            System.out.println("Сегодня пятница " + dayOneFriday + " -е число. Необходимо подготовить отчёт");
compete

2023-03-19 21:13 UTC, KlimovDima commented on src/Main.java
> +            yearFlyComet = yearFlyComet + cycleComet;
compete

2023-03-19 21:13 UTC, KlimovDima commented on src/Main.java
> +            System.out.println("Сумма накоплений за: " + month + " месяц равна " + amountMoney + " рублей");
complete

2023-03-20 06:55 UTC, safgbad approved these changes

2023-03-23 21:14 UTC, merged